apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:a6666b5faaf42e1b43cba31df04276c741c2e0ae334ae8688278255db5c79d53
  name: quay.io/usimpson/dotnetcore
  newName: quay.io/usimpson/dotnetcore
