apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:74c6d76e9b1ca1c7473c5b8f0915be536915ae254c62d776c6b2785787db0489
  name: quay.io/usimpson/dotnetcore
  newName: quay.io/usimpson/dotnetcore
